#
# installation
#

- include: source.yml
  when: use_source

- include: binary.yml
  when: not use_source

#
# post installation configuration
#

# TODO: move some configuration there when the documentation is clear and when
# the rpm packages are available

- name: Copy conf to remote
  copy:
    src=tendrl.conf
    dest=/etc/tendrl/tendrl.conf
