#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

- name: Copy conf to remote
  copy:
    src=tendrl.conf
    dest=/etc/tendrl/tendrl.conf
