- name: Install newest setuptools into virtualenv
  pip:
    name=setuptools
    state=latest
    virtualenv="{{ virtualenv_path }}"

- name: Directory for Tendrl virtualenv
  file:
    path="{{ virtualenv_path }}"
    state=directory

- name: Install common into virtualenv
  pip:
    name={{ tendrl_common_repo_url }}
    virtualenv="{{ virtualenv_path }}"

- name: Directory for Tendrl conf
  file:
    path={{ item }}
    state=directory
  with_items:
    - /etc/tendrl
    - /etc/tendrl/node_agent

- name: Directory for Tendrl log
  file:
    path={{ item }}
    state=directory
  with_items:
    - /var/log/tendrl
    - /var/log/tendrl/etc
    - /var/log/tendrl/etc/tendrl
    - /var/log/tendrl/etc/tendrl/ceph_integration
    - /var/log/tendrl/etc/tendrl/gluster_integration
    - /var/log/tendrl/node_agent
    - /var/log/tendrl/common
    - /var/log/tendrl/ceph_integration
    - /var/log/tendrl/gluster_integration

- name: Copy conf to remote
  copy:
    src=tendrl.conf
    dest=/etc/tendrl/tendrl.conf
