#
# installation
#

- include: source.yml
  when: use_source

- include: binary.yml
  when: not use_source

#
# post installation configuration
#

- name: Configure tendrl.conf - etcd_connection
  lineinfile:
    dest=/etc/tendrl/tendrl.conf
    regexp="^(\#*)etcd_connection = (.*)"
    line="etcd_connection = {{ hostvars[groups['usm_server'][0]]['ansible_eth0']['ipv4']['address'] }}"
