- name: Directory for Tendrl virtualenv
  file:
    path="{{ virtualenv_path }}"
    state=directory

- name: Clone tendrl.git
  git:
    repo={{ tendrl_node_agent_repo_url }}
    dest={{ tendrl_node_agent_path }}

- name: Create common logging config file
  shell: cp -r {{ tendrl_node_agent_path }}/etc/logging.yaml.timedrotation.sample /etc/tendrl/common_logging.yaml

- name: Create node_agent logging config file
  shell: cp -r {{ tendrl_node_agent_path }}/etc/logging.yaml.timedrotation.sample /etc/tendrl/node_agent_logging.yaml

- name: Install the 'Development tools' package group
  yum:
    name="@Development tools"
    state=present
  
# TODO: Find proper way how to install those prerequisities not mentioned in documentation
- name: Install dependencies
  yum:
    name={{ item }}
    state=present
  with_items:
    - libffi 
    - libffi-devel
    - openssl
    - openssl-devel

- name: Create directory for logging 
  file:
    path=/var/log/tendrl/common/node_agent
    state=directory

# TODO: install it correctly from requirements.txt
- name: Install node_agent prerequisities into virtualenv
  pip:
    name={{ item }}
    virtualenv="{{ virtualenv_path }}"
    state=latest
  with_items:
    - ansible
    - python-etcd
    - gevent
    - greenlet
    
- name: Install node_agent into virtualenv
  pip:
    name=.
    virtualenv="{{ virtualenv_path }}"
    chdir="{{ tendrl_node_agent_path }}"
