---
# HACK
# FIXME: There should be proper firewall configuration!

- hosts: gluster:usm_server
  remote_user: root
  tasks:
  - name: stop firewall
    service:
      name: firewalld
      state: stopped
      enabled: no
