---
# This playbook deploy ssh public key for usmqe user to qe_server.

- name: Deploy ssh public keys for root user account
  hosts: qe_server
  user: root
  tasks:
   - name: Deploy public ssh key
     authorized_key:
       exclusive=no
       user=usmqe
       state=present
       key="{{ item }}"
     with_items:
       - "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
