---
- hosts: usm_server 
  remote_user: root
  vars:
    use_source: true
  roles:
    - tendrl-devel
    - etcd
    - tendrl-api

- hosts: gluster
  remote_user: root
  vars:
    use_source: true
#    tendrl_gluster_bridge_repo_branch: vol-operations
  roles:
    - tendrl-devel
    - gluster
    - tendrl-bridge-common
    - tendrl-node-agent
    - tendrl-gluster-bridge
