---
- hosts: usm_server 
  remote_user: root
  vars:
    use_source: true
  roles:
    - tendrl-devel
    - etcd
    - tendrl-api

- hosts: gluster
  remote_user: root
  vars:
    use_source: true
  roles:
    - tendrl-devel
    - gluster
    - tendrl-common
    - tendrl-node-agent
    - tendrl-bridge
