---
- hosts: usm_server 
  remote_user: root
  vars:
    install_from: packages
    enable_repo: epel
  roles:
    - tendrl-devel
    - etcd
    - tendrl-repo
    - tendrl-api
#    - tendrl-frontend

- hosts: gluster
  remote_user: root
  vars:
    install_from: packages
    enable_repo: epel
  roles:
    - tendrl-devel
    - gluster-centos
    - tendrl-repo
    - tendrl-common
    - tendrl-node-agent
    - tendrl-gluster-integration

- include: qe_gluster_cluster.yml
