---
- hosts: usm_server 
  remote_user: root
  vars:
#    use_source: true
    use_epel: true
  roles:
    - tendrl-devel
    - etcd
    - tendrl-repo
    - tendrl-api
#    - tendrl-frontend

- hosts: gluster
  remote_user: root
  vars:
#    use_source: true
    use_epel: true
  roles:
    - tendrl-devel
    - gluster
    - tendrl-repo
    - tendrl-common
    - tendrl-node-agent
    - tendrl-gluster-integration
