#
# installation
#

- include: source.yml
  when: use_source

- include: binary.yml
  when: not use_source

#
# post installation configuration
#

# TODO: move some configuration there when the documentation is clear
