#
# installation
#

- include: source.yml
  when: install_from == "source"

- include: binary.yml
  when: install_from == "packages"

#
# post installation configuration
#

# TODO: move some configuration there when the documentation is clear
