- name: Install Ruby
  yum:
    name={{ item }}
    state=present
  with_items:
    - @development  # CentOS group id, could (will) be different for other OSes
    - ruby
    - ruby-devel

- name: Clone tendrl.git
  git:
    repo={{ tendrl_api_repo_url }}
    version={{ tendrl_api_repo_branch }}
    dest={{ tendrl_api_local_path }}

- name: Exclude files created by bundler from repo (HACK)
  command: git update-index --assume-unchanged Gemfile.lock
    chdir={{ tendrl_api_local_path }}

- name: Install Ruby bundler (HACK)
  gem:
    name=bundler

- name: Bundle installation of Tendrl (HACK)
  bundler:
    state=present
    binstub_directory={{ tendrl_api_bundle_install_path }}
    chdir={{ tendrl_api_local_path }}
  when: not tendrl_api_bundle_without

- name: Bundle installation of Tendrl (HACK)
  bundler:
    state=present
    binstub_directory={{ tendrl_api_bundle_install_path }}
    exclude_groups={{ tendrl_api_bundle_without_groups }}
    chdir={{ tendrl_api_local_path }}
  when: not tendrl_api_bundle_without

- name: Directory for config
  file:
    path={{ tendrl_api_local_path }}/config/sds
    state=directory

- name: Create config file with connection to etcd
  shell: cp -r {{ tendrl_api_local_path }}/config/etcd.sample.yml {{ tendrl_api_local_path }}/config/etcd.yml

- name: Copy yaml definition into proper directory
  shell: cp -r {{ tendrl_api_local_path }}/spec/fixtures/sds/tendrl_definitions_gluster-3.8.3.yaml {{ tendrl_api_local_path }}/config/sds/tendrl_definitions_gluster-3.8.3.yaml

- name: Configure config/etcd.yml - host
  lineinfile:
    dest={{ tendrl_api_local_path }}/config/etcd.yml
    regexp="^  {{ ":" }}host{{ ":" }} \'127.0.0.1\'"
    line="  {{ ":" }}{{ item }}{{ ":" }} \'{{ hostvars[groups['usm_server'][0]]['ansible_eth0']['ipv4']['address'] }}\'"
  with_items:
    - host
    - host
    - host

#- name: Make sure that ETCD service is running
#  service:
#    name=etcd
#    state=started

#- name: Seed the etcd instance
#  command: vendor/bin/rake etcd:seed
#    chdir={{ tendrl_api_local_path }}

- name: Start the development server
  command: vendor/bin/shotgun
    chdir={{ tendrl_api_local_path }}

## Running on Port 80
#- name: Install apache
#  yum: name={{ item }}
#    state=present
#  with_items:
#    httpd
#
#- name: Copy apache configuration
#  shell: cp {{ tendrl_api_local_path }}/config/apache.vhost.sample /etc/httpd/conf.d/tendrl.conf
#
## TODO update the apache config file to specific host details
#
#-name: check configuration
# command: apachectl configtest
#
#-name: Update the SELinux configuration for apache
# seboolean:
#    name=httpd_can_network_connect
#    state=yes
#    persistent=yes
#
#-name: Run the application via puma
# command: vendor/bin/puma -e development -d
#
#-name: Start apache
# service:
#    name=httpd
#    state=started
