- name: Install dependencies
  yum:
    name={{ item }}
  with_items:
    - @development  # CentOS group id, could (will) be different for other OSes
    - ruby
    - ruby-devel
    - rubygem-bundler
    - python-pip
    - git
    - nodejs
    - npm
    - httpd
    - python-devel
    - gcc
    - python-virtualenv
