- name: Clone gluster_bridge
  git:
    repo=git://github.com/shtripat/gluster_bridge.git
    dest={{ gluster_bridge_path }}
    version=vol-operations

- include: virtualenv.yml
  when: virtualenv_path is defined

- include: nonvirtualenv.yml
  when: not virtualenv_path
