- name: Install Ruby
  yum:
    name={{ item }}
    state=present
  with_items:
    - ruby 
    - ruby-devel

- name: Clone tendrl.git
  git:
#    repo=git://github.com/Tendrl/tendrl.git
    repo=git://github.com/anivargi/tendrl.git
    version=gluster-create-volume-api
    dest={{ api_path }}

- name: Exclude files created by bundler from repo
  command: git update-index --assume-unchanged Gemfile.lock
    chdir={{ api_path }}

- name: Install Ruby bundler
  gem:
    name=bundler

- name: Bundle installation of Tendrl
  bundler:
    state=present
    chdir={{ api_path }}

- name: Directory for config 
  file:
    path={{ api_path }}/config/sds
    state=directory

- name: Create config file with connection to ETCD
  shell: cp -r {{ api_path }}/config/etcd.sample.yml {{ api_path }}/config/etcd.yml

- name: Copy yaml definition into proper directory 
  shell: cp -r {{ api_path }}/spec/fixtures/sds/tendrl_definitions_gluster-3.8.3.yaml {{ api_path }}/config/sds/tendrl_definitions_gluster-3.8.3.yaml

- name: Configure config/etcd.yml - host
  lineinfile:
    dest={{ api_path }}/config/etcd.yml
    regexp="^  {{ ":" }}host{{ ":" }} \'127.0.0.1\'"
    line="  {{ ":" }}{{ item }}{{ ":" }} \'{{ hostvars[groups['usm_server'][0]]['ansible_eth0']['ipv4']['address'] }}\'"
  with_items:
    - host
    - host
    - host

- name: Make sure that ETCD service is running
  service:
    name=etcd
    state=started

- name: Seed the Etcd instance
  command: bundle exec rake etcd:seed 
    chdir={{ api_path }}
