#
# test if services run properly
#

# as documented in README file and deployment.adoc from Tendrl/documentation
- name: Start and enable tendrl-api
  service:
    name=tendrl-apid
    state=started
    enabled=yes

- name: Start and enable apache
  service:
    name=httpd
    state=started
    enabled=yes
